### ISSUE TITLE
gltf_fullScreen demo can not full screen when show shadow.

### ISSUE THREAD

**Issue by whilemouse** [jeeliz/jeelizFaceFilter#51] opened 2018-10-30 05:20 UTC
Hello, thanks for this good library.

I have question at demo.

#### Environment
Device: Mac OS
Browser: Chrome
I think It occurs in most environments.

#### demo file
gltf_fullScreen/index.html

#### Describe
I added spotLight(castShadow on) in this demo. At this time, renderer have border and not full screen.

#### Step
1. Go [demo](https://jeeliz.com/demos/faceFilter/demos/threejs/gltf_fullScreen/)
2. Browser developer console -> enter this code.
````javascript
THREERENDERER.shadowMap.enabled = true;
var spotLight = new THREE.SpotLight( 0xffffff );
spotLight.castShadow = true;
THREESCENE.add(spotLight)
````
3. At this time, created border and can't shown full screen

#### Additional context
I tried several attempts. It occurs by shadow. And this only occurs in this demo(maybe it's fullscreen). I hesitated very much to put this issue on here or on three js. I am sorry if it is a matter of three js.

Best,
whilemouse

**Comment by xavierjs** [comment] 2018-10-30 14:10
I can reproduce it with Chrome/Linux.

The problem is I forgot to put the line `THREERENDERER.setViewport(0,0, CANVASELEMENT.width, CANVASELEMENT.height);`
So the THREEJS viewport size was still 600 x 600 pixels
Before using shadow mapping THREE.JS had not to set the viewport because there was no shadowmap rendering. So all was OK.
But when you added a shadowmap THREE.JS has to change the viewport dimension to the shadowmap size, compute the shadow map, then it reset the viewport size with the wrong value (600x600px).
I have inserted the line:
```
THREERENDERER.setViewport(0,0, CANVASELEMENT.width, CANVASELEMENT.height);
```
at the end of the resize callback function.
I have pushed the correction

**Comment by whilemouse** [comment] 2018-10-30 22:55
I checked your pushed and try it


![image](https://user-images.githubusercontent.com/16111790/47755563-19e5a480-dce2-11e8-80fa-f8213deeaa18.png)

````javascsript
THREERENDERER.getViewPort();  // return {x: 0, y: -679, z: 1346, w: 1279}
````
y is not 0. I don't know why y gets a non-zero value, but I found a way to solve it. If you know why the value of y is not 0, you'll be thankful to let me know.
````javascript
function on_canvasResizeCSS() {
        var primitiveHeight = CANVASELEMENT.height;  // get primitive height.
        var canvasRect = CANVASELEMENT.getBoundingClientRect();
        CANVASELEMENT.width = Math.round(canvasRect.width);
        CANVASELEMENT.height = Math.round(canvasRect.height);
        var aspecRatio = CANVASELEMENT.width / CANVASELEMENT.height;
        THREECAMERA.aspect = aspecRatio;
        THREECAMERA.updateProjectionMatrix();
        THREERENDERER.setViewport(0, (CANVASELEMENT.height - primitiveHeight) * -1 , CANVASELEMENT.width, CANVASELEMENT.height);  // y = -(viewport height - primitive height)
        JEEFACEFILTERAPI.resize();      
    }
````

**Comment by xavierjs** [comment] 2018-10-31 00:11
Hi,
This is really strange because THREERENDERER.setViewport is a very light wrapper on the GL.viewport function.

it works from me if I add: `THREERENDERER.setSize(CANVASELEMENT.width, CANVASELEMENT.height);` just after `THREERENDERER.setViewport...`.

I have just pushed the commit :)

**Comment by whilemouse** [comment] 2018-10-31 00:30
Hi, @xavierjs 
I added this.
````javascript
THREERENDERER.setSize(CANVASELEMENT.width, CANVASELEMENT.height);
THREERENDERER.setViewport(0, 0, CANVASELEMENT.width, CANVASELEMENT.height);
````

The canvas size is fixed when you resize the window. So canvas leave a space.  Because of setSize(...)

~width: 100%~
~height: 100%~
````css
#jeeFaceFilterCanvas {
    width: 799px;
    height: 473px;
}
````

![image](https://user-images.githubusercontent.com/16111790/47758709-8dda7980-dcef-11e8-901a-a215522bc70e.png)

**Comment by xavierjs** [comment] 2018-10-31 00:57
ugggh you are right there is another bug now.
It is fixed by adding , false at the end of `THREERENDERER.setSize` call:
```
THREERENDERER.setSize(CANVASELEMENT.width, CANVASELEMENT.height, false);
```
The `false` is for the `updateStyle` parameter (set to true by default), it just tells THREE.JS to not change the CSS.

**Comment by whilemouse** [comment] 2018-10-31 01:01
Cool. It works.
I need more three.js study... thanks. :)

**Closed** 2018-10-31 01:01 UTC
