### ISSUE TITLE
Not work with smartphone Chrome Apple/Android

### ISSUE THREAD

**Issue by Luigixx89** [jeeliz/jeelizFaceFilter#129] opened 2019-09-26 14:02 UTC
Hi, i test jeeliz with my smartphone (Iphone) and not work.
i use google chrome. 
Works well with Safari... 
you can fix the problem on Chrome?

In chrome://flags is not present Enable webgl

*the demo doesn't even work VTO Widget 
Thanks

**Comment by xavierjs** [comment] 2019-09-26 14:14
Duplicate of #95

**Closed by xavierjs** 2019-09-26 14:14 UTC

**Comment by Luigixx89** [comment] 2019-09-26 14:26
ok thanks... how to do it in android?
with android use chrome and not work...egual firefox.
show request open camera, and not work.

Thanks

Il giorno gio 26 set 2019 alle ore 16:14 Bourry Xavier <
notifications@github.com> ha scritto:

**Comment by xavierjs** [comment] 2019-09-26 14:34
depends on the phone.
First close all apps using the camera and retry.
Then i can do nothing with such information: "It does not work on mine :("
Please provide informations required here: https://github.com/jeeliz/jeelizFaceFilter#compatibility

**Comment by Luigixx89** [comment] 2019-09-26 14:40
ok, thanks for the quick replies

Il giorno gio 26 set 2019 alle ore 16:34 Bourry Xavier <
notifications@github.com> ha scritto:

**Comment by xavierjs** [comment] 2020-12-11 21:57
**BREAKING NEWS**: Camera access is enabled on IOS14.3 which is released this Monday ( December 14th ). So FaceFilter will work on Chrome, Firefox, Opera for IOS, and into `WKWebviews` embedded in native apps.
