### ISSUE TITLE
Camera not closing 

### ISSUE THREAD

**Issue by dineshBD** [jeeliz/jeelizFaceFilter#148] opened 2019-12-02 22:30 UTC
Hi Xavier, I am using JEEFACEFILTERAPI.toggle_slow(true, true) to close the camera after the page is changed but I can still see the webcam light on. Am I missing anything?

**Comment by xavierjs** [comment] 2019-12-03 01:14
Duplicate of #101

**Closed by xavierjs** 2019-12-03 01:14 UTC
