### ISSUE TITLE
Switch between filters Feature request

### ISSUE THREAD

**Issue by ClarabelleCheng-Yue** [jeeliz/jeelizFaceFilter#150] opened 2019-12-18 22:36 UTC
Say a current filter is running and you want to switch to a different filter. The Jeeliz API does not have the ability to stop tracking and then switch to a different filter. It seems the first init() call prevents init() to be called again, causing the ALREADY_INITIALIZED error.
toggle_pause() stops the camera and callbackTrack() but does not fully stop Jeeliz such that one can initialize a different filter.

**Comment by xavierjs** [comment] 2019-12-19 01:39
duplicate of #74

**Closed by xavierjs** 2019-12-19 01:39 UTC
