### ISSUE TITLE
Ear, Nose, Neck detection

### ISSUE THREAD

**Issue by AkashNan** [jeeliz/jeelizFaceFilter#156] opened 2020-02-06 08:54 UTC
Hi All,

New here with Jeeliz, I have gone through the demos and I was wondering if I could quickly ask for possible application we can build with it.

Can we detect ear, nose and nect with jeeliz or not ? 

if I can then I can make jwellery AR  filter application or lipstick AR filter application. 

I have seen demos, I understood face tracking and detection is possible. Dog face demo detecting face but not ears it's just y position it's managing. 

Could you please let me know if individual face part tracking is possible or not?

**Comment by xavierjs** [comment] 2020-02-06 17:00
duplicate of #1

**Closed by xavierjs** 2020-02-06 17:00 UTC
