### ISSUE TITLE
Can you provide example with objloader?

### ISSUE THREAD

**Issue by filippozanardo** [jeeliz/jeelizFaceFilter#147] opened 2019-11-14 17:12 UTC
Hi,
i'm tryng to import an obj into FaceFilter, in plain threejs work when i add to the faceObject it display nothing? can you share an example using an obj?
Thanks a lot

**Comment by xavierjs** [comment] 2019-11-14 17:32
Hi,

Duplicate of #145

**Closed by xavierjs** 2019-11-14 17:32 UTC
